name: Build and install LLVM on Windows

on:
  # Allow running the workflow manually
  workflow_dispatch:
  # Run the workflow once a week
  schedule:
    - cron: '6 22 * * SUN'
  # Run the workflow when a push is made
  push:
    branches:
      - main
  # Run the workflow when a pull request is made
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build LLDB-MI and run the testsuite
    runs-on: windows-2019
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.5.0
      - name: Use local action install_llvm with default arguments
        uses: ./.github/actions/install_llvm
